# Generated by Django 6.1.1 on 2026-09-16 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('software', 'Software Engineering'), ('data_science', 'Data Science / ML'), ('product', 'Product Management'), ('design', 'UI/UX Design'), ('marketing', 'Marketing'), ('finance', 'Finance / Accounting'), ('hr', 'Human Resources'), ('sales', 'Sales'), ('other', 'Other')], default='software', max_length=50)),
                ('experience_years', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
